;----------------------------------------------------------
; Global defaults
;----------------------------------------------------------
[*]
n-gpu-layers       = -1
flash-attn         = on
parallel           = 1
ctx-size           = 92160
threads            = 8
batch-size         = 2048
ubatch-size        = 1024
cache-type-k       = q8_0
cache-type-v       = q8_0
cache-ram          = 16384
n-predict          = 32768
top-k              = 20
min-p              = 0.0
no-warmup          = true
cache-prompt       = true
threads-http       = 2
jinja              = true
load-on-startup    = false
sleep-idle-seconds = -1

;----------------------------------------------------------
; Per-model configurations
;----------------------------------------------------------
[qwen3.8-27b]
model                = /models/Qwen3.8-27B-UD-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.0
presence-penalty     = 0.0
repeat-penalty       = 1.0
reasoning            = off

[qwen3.8-27b-medium]
model                = /models/Qwen3.8-27B-UD-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.6
top-p                = 0.95
presence-penalty     = 0.5
repeat-penalty       = 1.0
reasoning            = on
;reasoning-type       = deepseek
reasoning-effort     = medium
reasoning-preserve   = true
reasoning-budget     = 16384

[qwen3.8-27b-high]
model                = /models/Qwen3.8-27B-UD-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.6
top-p                = 0.95
presence-penalty     = 0.5
repeat-penalty       = 1.0
reasoning            = on
;reasoning-type       = deepseek
reasoning-effort     = high
reasoning-preserve   = true
reasoning-budget     = 24576


[qwen3.8-27b-uncensored]
model                = /models/Huihui-Qwen3.8-27B-abliterated-UD-DW-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.0
presence-penalty     = 0.0
repeat-penalty       = 1.0
reasoning            = off

[qwen3.8-27b-uncensored-medium]
model                = /models/Huihui-Qwen3.8-27B-abliterated-UD-DW-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.6
top-p                = 0.95
presence-penalty     = 0.5
repeat-penalty       = 1.0
reasoning            = on
;reasoning-type       = deepseek
reasoning-effort     = medium
reasoning-preserve   = true
reasoning-budget     = 16384

[qwen3.8-27b-uncensored-high]
model                = /models/Huihui-Qwen3.8-27B-abliterated-UD-DW-Q4_K_XL.gguf
spec-type            = draft-mtp
spec-draft-n-max     = 4
temp                 = 0.6
top-p                = 0.95
presence-penalty     = 0.5
repeat-penalty       = 1.0
reasoning            = on
;reasoning-type       = deepseek
reasoning-effort     = high
reasoning-preserve   = true
reasoning-budget     = 24576
